### ISSUE TITLE
Create color palette

### ISSUE THREAD

**Issue by MSDimitrov23** [codingburgas/sprint-math-games-9th-grade-dsg#2]
Create a color palette and add it to a header file in the include folder. There should be colors for: text, background, secondary elements (borders, decorations), correct answer, incorrect answer
The variables should look like this:
```c++
inline constexpr Color text = Color{217, 203, 109, 255};
```
The colors are rgb and have a transparency which should always be 255.
In this example red = 217, blue = 203, green = 109.
Don't forget to include raylib.h

**Comment by KRParashkevov23** [comment]
If this is rgb, why is there a 4th value? Do you mean rgba (the "a" is the 4th value, which is transparency)?
